<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerELR5MND\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerELR5MND/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerELR5MND.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerELR5MND\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerELR5MND\App_KernelProdContainer([
    'container.build_hash' => 'ELR5MND',
    'container.build_id' => '408449a1',
    'container.build_time' => 1612009226,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerELR5MND');
