<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container06IerRx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container06IerRx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container06IerRx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container06IerRx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container06IerRx\App_KernelDevDebugContainer([
    'container.build_hash' => '06IerRx',
    'container.build_id' => 'c1156542',
    'container.build_time' => 1612006293,
], __DIR__.\DIRECTORY_SEPARATOR.'Container06IerRx');
