<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKwMgZSW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKwMgZSW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKwMgZSW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKwMgZSW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKwMgZSW\App_KernelDevDebugContainer([
    'container.build_hash' => 'KwMgZSW',
    'container.build_id' => 'c0c7ed08',
    'container.build_time' => 1608025562,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKwMgZSW');
